spring:
  datasource:
    url: jdbc:mysql://localhost:3306/suicidal
    username: root
    password: thapelo123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#  email configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: savealife.cosc300@gmail.com
    password: rbrllwfuwqglmdid
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 102803747181-8h70rrddnm1u52g1ar33d5a85u4k01s4.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
  
logging:
  level:
    org.springframework.security: DEBUG
